# Konfigurasi Server berjalan di port 8080
server.port=8080

# Konfigurasi Database H2
spring.datasource.url=jdbc:h2:mem:papikostdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Konfigurasi Hibernate / JPA (Agar tabel dibuat otomatis dari struktur class)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mengaktifkan antarmuka H2 di browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console